# Generated by Django 4.1 on 2022-10-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='is_answered',
        ),
    ]
