# Generated by Django 4.1 on 2022-10-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0006_alter_pengunjung_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('shipping_method', models.CharField(max_length=255)),
                ('shipping_kurir', models.CharField(default='none', max_length=255)),
                ('points', models.BigIntegerField(default=0)),
                ('pengunjung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.pengunjung')),
            ],
        ),
    ]
