# Generated by Django 4.1 on 2022-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_nama_barang_donationinfo_jenis_barang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationinfo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/donation/', verbose_name='Foto barang'),
        ),
        migrations.AlterField(
            model_name='donationinfo',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='donationinfo',
            name='shipping_method',
            field=models.CharField(choices=[('0', 'Antar sendiri'), ('1', 'JNE'), ('2', 'POS INDONESIA'), ('3', 'TIKI'), ('4', 'SiCepat'), ('5', 'J&T')], default=('0', 'Antar sendiri'), max_length=255, verbose_name='Metode pengiriman'),
        ),
    ]
