# Generated by Django 4.1 on 2022-10-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_donationinfo_foto_alter_donationinfo_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationinfo',
            name='foto',
        ),
    ]
