# Generated by Django 4.1 on 2022-10-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_pengunjung_user'),
        ('donation', '0005_donationinfo_waktu_isi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='pengunjung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.pengunjung'),
        ),
    ]
