# Generated by Django 4.1 on 2022-10-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_alter_donationinfo_pengunjung'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationinfo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationinfo',
            name='amount',
            field=models.IntegerField(verbose_name='Banyak (dalam kg)'),
        ),
        migrations.AlterField(
            model_name='donationinfo',
            name='shipping_method',
            field=models.CharField(choices=[('Antar sendiri', 'Antar sendiri'), ('JNE', 'JNE'), ('POS INDONESIA', 'POS INDONESIA'), ('TIKI', 'TIKI'), ('SiCepat', 'SiCepat'), ('J&T', 'J&T')], default=('Antar sendiri', 'Antar sendiri'), max_length=255, verbose_name='Metode pengiriman'),
        ),
    ]
