# Generated by Django 4.1 on 2022-10-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_donationinfo_waktu_isi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='waktu_isi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
