# Generated by Django 4.1 on 2022-10-28 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_alter_donationinfo_waktu_isi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='waktu_isi',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 7, 6, 15, 508626)),
        ),
    ]
