# Generated by Django 4.1 on 2022-10-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_alter_donationinfo_waktu_isi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationinfo',
            name='points',
        ),
    ]
