# Generated by Django 4.1 on 2022-11-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_remove_donationinfo_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationinfo',
            name='jenis_barang',
            field=models.CharField(max_length=255, verbose_name='Jenis Kain'),
        ),
    ]
