# Generated by Django 4.1 on 2022-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.TextField()),
                ('email_user', models.EmailField(max_length=254)),
                ('nomor_user', models.IntegerField()),
                ('pesan_user', models.TextField()),
            ],
        ),
    ]
