# Generated by Django 4.1 on 2022-11-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.TextField()),
                ('nama_belakang', models.TextField()),
                ('email_user', models.EmailField(max_length=254)),
                ('nomor_user', models.IntegerField()),
                ('pesan_user', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaDepan', models.CharField(max_length=255)),
                ('namaBelakang', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
