# Generated by Django 4.1 on 2022-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=('XS', 'XS'), max_length=255, verbose_name='Ukuran pakaian')),
                ('payment_method', models.CharField(choices=[('BCA', 'BCA'), ('MANDIRI', 'MANDIRI'), ('BNI', 'BNI'), ('BRI', 'BRI'), ('PAYPAL', 'PAYPAL')], default=('BCA', 'BCA'), max_length=255, verbose_name='Tipe Pembayaran')),
                ('shipping_method', models.CharField(choices=[('Antar sendiri', 'Antar sendiri'), ('JNE', 'JNE'), ('POS INDONESIA', 'POS INDONESIA'), ('TIKI', 'TIKI'), ('SiCepat', 'SiCepat'), ('J&T', 'J&T')], default=('Antar sendiri', 'Antar sendiri'), max_length=255, verbose_name='Metode pengiriman')),
            ],
        ),
    ]
