# Generated by Django 4.1 on 2022-11-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_shop_pengunjung_alter_shop_shipping_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='type',
            new_name='tipe',
        ),
    ]
