# Generated by Django 4.1 on 2022-10-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('jenis_kelamin', models.CharField(choices=[('LK', 'Laki-Laki'), ('PP', 'Perempuan')], max_length=2)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('kontak', models.CharField(max_length=13)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
    ]
