# Generated by Django 4.1 on 2022-10-21 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengunjung',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='pengunjung',
            name='password2',
        ),
        migrations.AddField(
            model_name='pengunjung',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='jenis_kelamin',
            field=models.CharField(choices=[('LK', 'Laki-Laki'), ('PP', 'Perempuan')], default='LK', max_length=2),
        ),
    ]
