# Generated by Django 4.1 on 2022-10-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_pengunjung_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='alamat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pengunjung',
            name='kontak',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
