# Generated by Django 4.1 on 2022-10-22 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0004_alter_pengunjung_alamat_alter_pengunjung_kontak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='user',
            field=models.OneToOneField(blank=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
