# Generated by Django 4.1 on 2022-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_pengunjung_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengunjung',
            name='poin',
            field=models.IntegerField(default=0),
        ),
    ]
