# Generated by Django 4.1 on 2022-11-02 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Authentication', '0008_alter_pengunjung_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengunjung',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
